openapi: '3.0.1'
info:
  title: Date App API
  version: '1.0.0'
  description: API for managing user profiles and images
servers:
  - url: http://localhost:5174/api/v1
paths:
  /profile/images:
    post:
      summary: Upload a new user image
      tags:
        - Images
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - upload limit reached
        '415':
          description: Unsupported Media Type
        '413':
          description: Payload Too Large
    get:
      summary: List user's images
      tags:
        - Images
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of user images
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Image'
        '401':
          description: Unauthorized
  /profile/images/{imageId}:
    delete:
      summary: Delete a user image
      tags:
        - Images
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: imageId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Image deleted
        '401':
          description: Unauthorized
        '404':
          description: Image not found
  /users/{userId}/upload-avatar:
    post:
      summary: Upload a profile avatar for a user
      tags:
        - Images
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user uploading the image
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Image uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Image'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden - upload limit reached or wrong user
        '500':
          description: Server error
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Image:
      type: object
      properties:
        id:
          type: string
        url:
          type: string
        owner:
          type: string
        is_profile_picture:
          type: boolean
        created_at:
          type: string
          format: date-time
        uploaded:
          type: string
          format: date-time
