services:
  mongo:
    image: mongo:6.0
    container_name: dateapp-mongo
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: dateapp-server
    restart: unless-stopped
    env_file:
      - ./server/.env
    environment:
      MONGO_URI: >-
        mongodb://${MONGO_INITDB_ROOT_USERNAME:-root}:${MONGO_INITDB_ROOT_PASSWORD:-changeme}@mongo:27017/${MONGO_DB_NAME:-loventia}?authSource=admin
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${SERVER_PORT:-5000}
    ports:
      - '${SERVER_PORT:-5000}:5000'
    depends_on:
      - mongo
    volumes:
      - type: bind
        source: ./server/uploads
        target: /usr/src/app/uploads
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dateapp-client
    restart: unless-stopped
    env_file:
      - ./client/.env
    ports:
      - '${CLIENT_PORT:-80}:80'
    depends_on:
      - server
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:${CLIENT_PORT:-80}/index.html >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  mongo_data: {}
