version: '3.8'

services:
  mongo:
    image: mongo:6.0-alpine
    container_name: dateapp-mongo
    restart: unless-stopped
    env_file:
      # contains MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD
      - "./server/.env"
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - "mongo_data:/data/db"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: dateapp-server
    restart: unless-stopped
    env_file:
      - "./server/.env"
    ports:
      - "${SERVER_PORT:-5000}:5000"
    volumes:
      - "./server:/usr/src/app"         # host source for hot-reload
      - "/usr/src/app/node_modules"     # container-only modules
    depends_on:
      - mongo
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT:-5000}/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: dateapp-client
    restart: unless-stopped
    env_file:
      - "./client/.env"
    ports:
      - "${CLIENT_PORT:-5174}:80"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    depends_on:
      - server
    command: npm run dev

volumes:
  mongo_data:
    name: mongo_data
