services:
  server:
    environment:
      - NODE_ENV=production
    volumes:
      - type: bind
        source: ./server/uploads
        target: /usr/src/app/uploads

  client:
    environment:
      - NODE_ENV=production
