// 📁 File: src/utils/locationData.js (Part 1 of 2)

// Translated static data: country and region names in English
export const countryRegions = {
  Argentina: ["Buenos Aires", "Córdoba"],
  Australia: [
    "New South Wales",
    "Victoria",
    "Queensland",
    "Western Australia",
    "South Australia",
  ],
  Austria: ["Vienna", "Lower Austria", "Upper Austria", "Tyrol", "Styria"],
  Bangladesh: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  Belgium: ["Flanders", "Wallonia", "Brussels-Capital Region"],
  Brazil: [
    "São Paulo",
    "Rio de Janeiro",
    "Bahia",
  ],
  Bulgaria: ["Sofia", "Plovdiv", "Varna", "Burgas"],
  Canada: [
    "Ontario",
    "Québec",
    "British Columbia",
    "Alberta",
    "Manitoba",
    "Saskatchewan",
    "Nova Scotia",
    "Newfoundland",
  ],
  Chile: ["Santiago Metropolitan", "Valparaíso"],
  China: [
    "Beijing",
    "Shanghai",
    "Guangdong",
    "Sichuan",
    "Zhejiang",
    "Hubei",
    "Shandong",
    "Yunnan",
  ],
  Colombia: ["Bogotá", "Antioquia", "Valle del Cauca", "Atlántico"],
  Croatia: ["Zagreb", "Split-Dalmatia", "Rijeka", "Osijek-Baranja"],
  "Czech Republic": ["Prague", "Brno", "Ostrava", "Pilsen"],
  Denmark: [
    "Capital Region",
    "Central Denmark",
    "Southern Denmark",
    "North Denmark",
  ],
  Egypt: ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan"],
  Finland: [
    "Uusimaa",
    "Pirkanmaa",
    "Southwest Finland",
    "East Finland and Savo",
    "North Karelia",
    "Lapland",
    "Ostrobothnia",
    "Kymenlaakso",
    "Päijät-Häme",
    "South Karelia",
  ],
  France: [
    "Île-de-France",
    "Provence",
    "Alsace",
    "Normandy",
    "Brittany",
    "Pays de la Loire",
    "Nouvelle-Aquitaine",
    "Occitanie",
  ],
  Germany: [
    "Bavaria",
    "Berlin",
    "North Rhine-Westphalia",
    "Hesse",
    "Saxony",
    "Brandenburg",
    "Baden-Württemberg",
    "Hamburg",
  ],
  Greece: ["Attica", "Central Macedonia", "Crete", "West Greece", "Thessaly"],
  Hungary: ["Budapest", "Debrecen", "Szeged", "Miskolc"],
  India: ["Maharashtra", "Delhi", "Tamil Nadu", "Karnataka"],
  Indonesia: ["Jakarta", "West Java", "Central Java", "East Java", "Bali"],
  Iran: ["Tehran", "Isfahan", "Shiraz", "Tabriz", "Mashhad", "Qom"],
  Iraq: ["Baghdad", "Basra", "Erbil", "Kirkuk", "Mosul"],
  Ireland: ["Dublin", "Cork", "Limerick", "Galway"],
  Israel: ["Beersheba", "Haifa", "Jerusalem", "Tel Aviv"],
  Italy: [
    "Lazio",
    "Lombardia",
    "Veneto",
    "Toscana",
    "Sicilia",
    "Puglia",
    "Piemonte",
    "Emilia-Romagna",
  ],
  Japan: [
    "Tokyo",
    "Osaka",
    "Kyoto",
    "Hokkaido",
    "Fukuoka",
    "Okinawa",
    "Aichi",
    "Hiroshima",
  ],
  Kazakhstan: ["Almaty", "Astana", "Shymkent", "Karaganda"],
  Latvia: ["Riga", "Latgale", "Kurzeme", "Zemgale"],
  Lithuania: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai"],
  Malaysia: ["Kuala Lumpur", "Selangor", "Johor", "Penang", "Sabah"],
  Mexico: [
    "Mexico City",
    "Jalisco",
    "Nuevo León",
    "Puebla",
    "Yucatán",
    "Chiapas",
    "Guanajuato",
    "Baja California",
  ],
  Netherlands: [
    "North Holland",
    "South Holland",
    "Utrecht",
    "Groningen",
    "Limburg",
  ],
  Nigeria: ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt"],
  Norway: [
    "Oslo",
    "Bergen",
    "Trøndelag",
    "Troms og Finnmark",
    "Vestland",
    "Innlandet",
    "Agder",
    "Nordland",
  ],
  Pakistan: ["Punjab", "Sindh", "Khyber Pakhtunkhwa", "Balochistan", "Islamabad"],
  Philippines: ["Metro Manila", "Cebu", "Davao Region", "Western Visayas"],
  Poland: [
    "Greater Poland",
    "Kuyavian-Pomeranian",
    "Lesser Poland",
    "Łódź",
    "Lower Silesian",
    "Lublin",
    "Lubusz",
    "Masovian",
    "Opole",
    "Podlaskie",
    "Pomeranian",
    "Silesian",
    "Subcarpathian",
    "Świętokrzyskie",
    "Warmian-Masurian",
    "West Pomeranian",
  ], // --- REPLACE START: Added Poland regions
// --- REPLACE END
  Portugal: ["Lisbon District", "Porto District"],
  Romania: ["Bucharest", "Cluj", "Timiș", "Iași"],
  Russia: ["Moscow", "Saint Petersburg", "Siberia"],
  "Saudi Arabia": ["Riyadh", "Mecca", "Medina", "Jeddah", "Dammam"],
  Slovakia: ["Bratislava", "Košice", "Prešov", "Žilina"],
  Slovenia: ["Ljubljana", "Maribor", "Celje", "Koper"],
  "South Africa": ["Gauteng", "Western Cape", "KwaZulu-Natal", "Eastern Cape"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  Spain: ["Madrid Region", "Catalonia", "Andalusia"],
  Sweden: [
    "Stockholm",
    "Skåne",
    "Västra Götaland",
    "Uppsala",
    "Örebro",
    "Värmland",
    "Dalarna",
    "Jämtland",
  ],
  Switzerland: ["Zürich", "Geneva", "Vaud", "Ticino"],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Isan", "Krabi"],
  Turkey: ["Istanbul", "Ankara", "Izmir", "Antalya", "Bursa", "Gaziantep"],
  "United Kingdom": [
    "England",
    "Scotland",
    "Wales",
    "Northern Ireland",
    "Greater London",
    "West Midlands",
    "Yorkshire",
    "Kent",
  ],
  "United States": [
    "California",
    "Texas",
    "New York",
    "Florida",
    "Illinois",
    "Washington",
    "Georgia",
    "Ohio",
    "Washington, D.C.",
  ],
  "Vatican City": ["Vatican City"],
  Vietnam: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Can Tho"],
};

export const regionCities = {
  Argentina: {
    "Buenos Aires": ["Avellaneda", "Buenos Aires", "La Plata", "Morón"],
    Córdoba: ["Córdoba", "Río Cuarto", "San Francisco", "Villa María"],
  },
   Australia: {
    "New South Wales": ["Newcastle", "Parramatta", "Sydney", "Wollongong"],
    Victoria: ["Ballarat", "Bendigo", "Geelong", "Melbourne"],
    Queensland: ["Brisbane", "Cairns", "Gold Coast", "Townsville"],
    "Western Australia": ["Albany", "Bunbury", "Fremantle", "Perth"],
    "South Australia": ["Adelaide", "Mount Gambier", "Port Augusta", "Whyalla"],
  },
  Austria: {
    Vienna: ["Vienna"],
    "Lower Austria": ["St. Pölten", "Wiener Neustadt"],
    "Upper Austria": ["Linz", "Wels"],
    Tyrol: ["Innsbruck", "Hall in Tirol"],
    Styria: ["Graz", "Leoben"],
  },
  Bangladesh: {
    Dhaka: ["Dhaka City", "Gulshan", "Mirpur"],
    Chittagong: ["Chittagong City", "Cox's Bazar"],
    Khulna: ["Khulna City", "Jessore"],
    Rajshahi: ["Rajshahi City", "Pabna"],
    Sylhet: ["Sylhet City", "Moulvibazar"],
  },
  Belgium: {
    Flanders: ["Antwerp", "Ghent"],
    Wallonia: ["Liège", "Namur"],
    "Brussels-Capital Region": ["Brussels"],
  },
  Bulgaria: {
    Sofia: ["Sofia"],
    Plovdiv: ["Plovdiv"],
    Varna: ["Varna"],
    Burgas: ["Burgas"],
  },
  Canada: {
    Ontario: ["Toronto", "Ottawa"],
    Québec: ["Montréal", "Québec City"],
    "British Columbia": ["Vancouver", "Victoria"],
    Alberta: ["Calgary", "Edmonton"],
    Manitoba: ["Winnipeg"],
    Saskatchewan: ["Regina"],
    "Nova Scotia": ["Halifax"],
    Newfoundland: ["St. John's"],
  },
  Chile: {
    "Santiago Metropolitan": ["Santiago", "Maipú"],
    Valparaíso: ["Valparaíso", "Viña del Mar"],
  },
  China: {
    Beijing: ["Haidian", "Chaoyang"],
    Shanghai: ["Pudong", "Xuhui"],
    Guangdong: ["Guangzhou", "Shenzhen"],
    Sichuan: ["Chengdu", "Mianyang"],
    Zhejiang: ["Hangzhou", "Ningbo"],
    Hubei: ["Wuhan", "Huangshi"],
    Shandong: ["Jinan", "Qingdao"],
    Yunnan: ["Kunming", "Dali"],
  },
  Colombia: {
    Bogotá: ["Bogotá", "Suba"],
    Antioquia: ["Medellín", "Envigado"],
    "Valle del Cauca": ["Cali", "Palmira"],
    Atlántico: ["Barranquilla", "Soledad"],
  },
  Croatia: {
    Zagreb: ["Zagreb"],
    "Split-Dalmatia": ["Split"],
    "Rijeka": ["Rijeka"],
    "Osijek-Baranja": ["Osijek"],
  },
  "Czech Republic": {
    Prague: ["Prague"],
    Brno: ["Brno"],
    Ostrava: ["Ostrava"],
    Pilsen: ["Pilsen"],
  },
  Denmark: {
    "Capital Region": ["Copenhagen", "Frederiksberg"],
    "Central Denmark": ["Aarhus", "Randers"],
    "Southern Denmark": ["Odense", "Vejle"],
    "North Denmark": ["Aalborg", "Hjørring"],
  },
  Egypt: {
    Cairo: ["Cairo", "Giza"],
    Alexandria: ["Alexandria", "Borg El Arab"],
    Giza: ["Giza"],
    Luxor: ["Luxor"],
    Aswan: ["Aswan"],
  },
  Finland: {
    Uusimaa: ["Helsinki", "Espoo"],
    Pirkanmaa: ["Tampere", "Nokia"],
    "Southwest Finland": ["Turku", "Salo"],
    "East Finland and Savo": ["Kuopio", "Varkaus"],
    "North Karelia": ["Joensuu", "Nurmes"],
    Lapland: ["Rovaniemi", "Kemi"],
    Ostrobothnia: ["Vaasa", "Seinäjoki"],
    Kymenlaakso: ["Kotka", "Kouvola"],
    "Päijät-Häme": ["Lahti", "Orimattila"],
    "South Karelia": ["Lappeenranta", "Imatra"],
  },
  France: {
    "Île-de-France": ["Paris", "Versailles"],
    Provence: ["Marseille", "Nice"],
    Alsace: ["Strasbourg", "Mulhouse"],
    Normandy: ["Rouen", "Caen"],
    Brittany: ["Rennes", "Brest"],
    "Pays de la Loire": ["Nantes", "Angers"],
    "Nouvelle-Aquitaine": ["Bordeaux", "Limoges"],
    Occitanie: ["Toulouse", "Montpellier"],
  },
  Germany: {
    Bavaria: ["Munich", "Nuremberg"],
    Berlin: ["Berlin"],
    "North Rhine-Westphalia": ["Cologne", "Düsseldorf"],
    Hesse: ["Frankfurt", "Wiesbaden"],
    Saxony: ["Leipzig", "Dresden"],
    Brandenburg: ["Potsdam", "Cottbus"],
    "Baden-Württemberg": ["Stuttgart", "Mannheim"],
    Hamburg: ["Hamburg"],
  },
  Greece: {
    Attica: ["Athens", "Piraeus"],
    "Central Macedonia": ["Thessaloniki", "Katerini"],
    Crete: ["Heraklion", "Chania"],
    "West Greece": ["Patras", "Agrinio"],
    Thessaly: ["Larissa", "Volos"],
  },
  Hungary: {
    Budapest: ["Budapest"],
    Debrecen: ["Debrecen"],
    Szeged: ["Szeged"],
    Miskolc: ["Miskolc"],
  },
  India: {
    Maharashtra: ["Mumbai", "Pune"],
    Delhi: ["New Delhi", "Dwarka"],
    "Tamil Nadu": ["Chennai", "Coimbatore"],
    Karnataka: ["Bangalore", "Mysore"],
  },
  Indonesia: {
    Jakarta: ["Central Jakarta", "South Jakarta"],
    "West Java": ["Bandung", "Bekasi"],
    "Central Java": ["Semarang", "Surakarta"],
    "East Java": ["Surabaya", "Malang"],
    Bali: ["Denpasar", "Ubud"],
  },
  Iran: {
    Tehran: ["Tehran", "Karaj"],
    Isfahan: ["Isfahan", "Kashan"],
    Shiraz: ["Shiraz", "Marvdasht"],
    Tabriz: ["Tabriz", "Marand"],
    Mashhad: ["Mashhad", "Sabzevar"],
    Qom: ["Qom"],
  },
  Iraq: {
    Baghdad: ["Baghdad", "Sadr City"],
    Basra: ["Basra", "Zubair"],
    Erbil: ["Erbil", "Shaqlawa"],
    Kirkuk: ["Kirkuk", "Dibis"],
    Mosul: ["Mosul", "Bashiqa"],
  },
  Ireland: {
    Dublin: ["Dublin", "Dún Laoghaire"],
    Cork: ["Cork"],
    Limerick: ["Limerick"],
    Galway: ["Galway"],
  },
  Israel: {
    Beersheba: ["Beersheba", "Dimona"],
    Haifa: ["Haifa", "Kiryat Ata"],
    Jerusalem: ["Jerusalem", "Bethlehem"],
    "Tel Aviv": ["Tel Aviv", "Ramat Gan"],
  },
  Italy: {
    Lazio: ["Rome", "Frosinone"],
    Lombardia: ["Milan", "Bergamo"],
    Veneto: ["Venice", "Verona"],
    Toscana: ["Florence", "Pisa"],
    Sicilia: ["Palermo", "Catania"],
    Puglia: ["Bari", "Lecce"],
    Piemonte: ["Turin", "Alessandria"],
    "Emilia-Romagna": ["Bologna", "Parma"],
  },
  Japan: {
    Tokyo: ["Tokyo", "Shinjuku"],
    Osaka: ["Osaka", "Sakai"],
    Kyoto: ["Kyoto", "Uji"],
    Hokkaido: ["Sapporo", "Hakodate"],
    Fukuoka: ["Fukuoka", "Kitakyushu"],
    Okinawa: ["Naha", "Okinawa City"],
    Aichi: ["Nagoya", "Toyota"],
    Hiroshima: ["Hiroshima", "Fukuyama"],
  },
  Kazakhstan: {
    Almaty: ["Almaty", "Esik"],
    Astana: ["Astana", "Karaganda"],
    Shymkent: ["Shymkent", "Turkistan"],
    Karaganda: ["Karaganda", "Balkhash"],
  },
  Latvia: {
    Riga: ["Riga"],
    Latgale: ["Daugavpils", "Rezekne"],
    Kurzeme: ["Liepaja", "Ventspils"],
    Zemgale: ["Jelgava", "Jekabpils"],
  },
  Lithuania: {
    Vilnius: ["Vilnius", "Kaunas"],
    Klaipėda: ["Klaipeda", "Siauliai"],
    Panevėžys: ["Panevezys"],
    Alytus: ["Alytus"],
  },
  Malaysia: {
    "Kuala Lumpur": ["Kuala Lumpur", "Petaling Jaya"],
    Selangor: ["Shah Alam", "Petaling Jaya"],
    Johor: ["Johor Bahru", "Batu Pahat"],
    Penang: ["George Town", "Bayan Lepas"],
    Sabah: ["Kota Kinabalu", "Sandakan"],
  },
  Mexico: {
    "Mexico City": ["Ciudad de Mexico", "Ecatepec"],
    Jalisco: ["Guadalajara", "Zapopan"],
    "Nuevo León": ["Monterrey", "San Nicolas"],
    Puebla: ["Puebla", "Tehuacan"],
    Yucatán: ["Merida", "Valladolid"],
  },
  Netherlands: {
    "North Holland": ["Amsterdam", "Haarlem"],
    "South Holland": ["Rotterdam", "The Hague"],
    Utrecht: ["Utrecht"],
    Groningen: ["Groningen"],
    Limburg: ["Maastricht"],
  },
  Nigeria: {
    Lagos: ["Lagos", "Ikeja"],
    Abuja: ["Abuja", "Gwagwalada"],
    Kano: ["Kano", "Wudil"],
  },
  Norway: {
    Oslo: ["Oslo", "Bergen"],
    "Trøndelag": ["Trondheim", "Stjørdal"],
    "Troms og Finnmark": ["Tromso", "Alta"],
    "Vestland": ["Bergen", "Voss"],
    "Innlandet": ["Lillehammer", "Hamar"],
  },
  Pakistan: {
    Punjab: ["Lahore", "Faisalabad"],
    Sindh: ["Karachi", "Hyderabad"],
  },
  Philippines: {
    "Metro Manila": ["Manila", "Quezon City"],
    Cebu: ["Cebu City", "Lapu-Lapu"],
    "Davao Region": ["Davao City"],
  },
  Poland: {
    "Greater Poland": ["Poznan", "Kalisz"],
    "Kuyavian-Pomeranian": ["Bydgoszcz", "Torun"],
    "Lesser Poland": ["Krakow", "Tarnow"],
    "Masovian": ["Warsaw", "Radom"],
    Silesian: ["Katowice", "Gliwice"],
  },
  Portugal: {
    "Lisbon District": ["Lisbon", "Sintra"],
    "Porto District": ["Porto", "Braga"],
  },
  Romania: {
    Bucharest: ["Bucharest"],
    Cluj: ["Cluj-Napoca"],
    Timis: ["Timisoara"],
    Iasi: ["Iasi"],
  },
  Russia: {
    Moscow: ["Moscow", "Khimki"],
    "Saint Petersburg": ["Saint Petersburg", "Pushkin"],
    Siberia: ["Novosibirsk"],
  },
  SaudiArabia: {
    Riyadh: ["Riyadh"],
    Mecca: ["Mecca"],
    Medina: ["Medina"],
  },
  Slovakia: {
    Bratislava: ["Bratislava"],
    Kosice: ["Kosice"],
  },
  Slovenia: {
    Ljubljana: ["Ljubljana"],
    Maribor: ["Maribor"],
  },
  "South Africa": {
    Gauteng: ["Johannesburg"],
    "Western Cape": ["Cape Town"],
  },
  "South Korea": {
    Seoul: ["Seoul", "Gangnam"],
    Busan: ["Busan"],
  },
  Spain: {
    "Madrid Region": ["Madrid"],
    Catalonia: ["Barcelona"],
  },
  Sweden: {
    Stockholm: ["Stockholm"],
    Skane: ["Malmo"],
  },
  Switzerland: {
    Zurich: ["Zurich"],
    Geneva: ["Geneva"],
  },
  Thailand: {
    Bangkok: ["Bangkok"],
    "Chiang Mai": ["Chiang Mai"],
  },
  Turkey: {
    Istanbul: ["Istanbul"],
    Ankara: ["Ankara"],
  },
  "United Kingdom": {
    England: ["London"],
    Scotland: ["Edinburgh"],
  },
  "United States": {
    California: ["Los Angeles", "San Francisco"],
    Texas: ["Houston", "Dallas"],
    "New York": ["New York City", "Buffalo"],
    Florida: ["Miami", "Orlando"],
  },
};
