groups:

name: sla.rules
rules:

alert: HighErrorRate
expr: job:request_errors:rate5m > 0.05
for: 10m
labels:
severity: critical
annotations:
summary: 'Korkea virheiden määrä API-kutsissa'
description: 'Virhesuhde yli 5% viimeisen 10 minuutin aikana.'
