env:

  TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
  PERF_PASSWORD: ${{ secrets.PERF_PASSWORD }}
  CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
# --- REPLACE START: client CI with unit + lighthouse + i18n audit ---
name: client-ci-qa

on:
  pull_request:
  push:
    branches: [ main, develop ]

jobs:
  client-qa:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install
        run: npm ci

      - name: Unit tests (Vitest)
        run: npm test -- --run

      - name: Build
        run: npm run build

      - name: Preview server (static)
        run: npm run preview &
      
      - name: Wait for preview
        run: npx wait-on http://localhost:4173

      - name: Lighthouse CI (against local preview)
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            http://localhost:4173
          configPath: ./lighthouse-budget.json
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: i18n audit
        run: npm run i18n:audit
# --- REPLACE END ---
