env:

  TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
  PERF_PASSWORD: ${{ secrets.PERF_PASSWORD }}
  CYPRESS_TEST_PASSWORD: ${{ secrets.CYPRESS_TEST_PASSWORD }}
# File: .github/workflows/cypress-e2e.yml

name: Cypress E2E Tests

on:
  push:
    branches: [ main, varaoksa14 ]   # --- REPLACE START: added feature branch for CI validation
  pull_request:
    branches: [ main, varaoksa14 ]   # --- REPLACE END

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress E2E
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 60
          command: npm run cy:run

      # Upload videos and screenshots produced by Cypress
      - name: Archive Cypress videos and screenshots
        # --- REPLACE START: bump deprecated upload-artifact v3 -> v4 (GitHub Actions requirement)
        uses: actions/upload-artifact@v4
        # --- REPLACE END
        with:
          name: cypress-artifacts
          # Keep both folders; newline-separated paths are recommended
          path: |
            cypress/videos
            cypress/screenshots
